// packages/photon-grid-angular/src/library/angular-renderer.adapter.ts
import {
    ApplicationRef,
    ComponentRef,
    EmbeddedViewRef,
    EnvironmentInjector,
    Injector,
    TemplateRef,
    createComponent,
} from '@angular/core';
import type { Type } from '@angular/core';

import type {
    ColumnDef,
    DetailComponent,
    DetailComponentConstructor,
    DetailContext,
    DetailRenderer,
    GridOptions,
    RendererOutput,
} from 'photon-grid-core';

import {
    AngularDetailRenderer,
    CellRenderer,
    ColumnRendererMap,
    ColumnDef as GridColumnDef,
    DetailTemplateContext,
    PhotonGridOptions,
    RendererContext,
    isComponentRendererSpec,
    isTemplateRendererSpec,
} from './angular-renderer.types';

type RendererMount =
    | { readonly kind: 'component'; readonly ref: ComponentRef<unknown> }
    | { readonly kind: 'template'; readonly ref: EmbeddedViewRef<unknown> };

type GridLifecycleMethod = 'pgGridInit' | 'pgGridRefresh' | 'pgGridDestroy';

/**
 * `true` when `renderer` is the per-slot override map rather than one of the
 * core's shorthand forms (a built-in name, a `{ name, options }` spec, or a
 * bare display function).
 *
 * A type predicate rather than an inline `typeof` chain because the core's
 * `ColumnRenderer` includes `string & {}` — the trick that keeps editor
 * completion on the built-in names while still admitting a custom one — and
 * `typeof x !== 'object'` does not narrow that away.
 */
function isRendererSlotMap(renderer: unknown): renderer is ColumnRendererMap {
    return typeof renderer === 'object' && renderer !== null && !('name' in renderer);
}

/**
 * Bridges the framework-agnostic `ColumnRendererMap` (plain functions
 * returning `HTMLElement | string`) to Angular components and templates.
 *
 * One instance is owned per `<photon-grid>` and lives for the component's
 * lifetime: {@link adaptColumns} is called whenever columns are (re)supplied,
 * and {@link dispose} is called once, in `ngOnDestroy`, to guarantee nothing
 * outlives the host component.
 *
 * ### Why a MutationObserver
 * The core owns cell/row virtualization and recycling; it has no lifecycle
 * hook that tells us "this cell's DOM node is gone, destroy whatever you
 * mounted into it". Since every renderer invocation mounts a *fresh*
 * component/embedded view (the core's contract is "produce output for these
 * params", not "patch existing output"), the only reliable place to catch
 * disposal is watching the DOM itself: when the core removes/replaces a
 * mounted host element, a MutationObserver on the grid root sees it and we
 * destroy the corresponding Angular view right then. This is what keeps
 * scrolling/virtualized grids from leaking components.
 */
export class RendererAdapter {
    /** Host element -> live Angular view mounted into it. */
    private readonly mounts = new Map<HTMLElement, RendererMount>();

    private observer?: MutationObserver;

    constructor(
        private readonly appRef: ApplicationRef,
        private readonly environmentInjector: EnvironmentInjector,
        private readonly elementInjector: Injector,
    ) {}

    /**
     * Starts watching `root` for node removals so mounted views can be torn
     * down as soon as the core discards their host element. Safe to call
     * repeatedly (e.g. across grid recreation) — any previous observer is
     * disconnected first, but existing mounts are left untouched.
     */
    observe(root: HTMLElement): void {
        this.observer?.disconnect();

        this.observer = new MutationObserver((mutations) => {
            // Bounded by the number of *currently mounted* renderer views
            // (i.e. visible custom cells), not by row/data-set size, because
            // virtualization keeps that number small regardless of grid size.
            if (this.mounts.size === 0) {
                return;
            }
            for (const mutation of mutations) {
                mutation.removedNodes.forEach((node) => this.cleanupRemovedNode(node));
            }
        });

        this.observer.observe(root, { childList: true, subtree: true });
    }

    /** Recursively converts `GridColumnDef[]` into plain `ColumnDef[]`. */
    adaptColumns(columns: readonly GridColumnDef[]): ColumnDef[] {
        return columns.map((column) => this.adaptColumn(column));
    }

    /**
     * Converts Angular-flavoured grid options into what the core accepts.
     *
     * Currently that is `masterDetail.renderer`: an `<ng-template>` or an
     * Angular component is wrapped in a core `DetailComponent` class that owns
     * its embedded view / component ref and disposes it in `destroy()`.
     *
     * Returns the original object untouched when there is nothing Angular to
     * adapt, so the common case allocates nothing.
     */
    adaptOptions(options: Partial<PhotonGridOptions>): Partial<GridOptions> {
        const masterDetail = options.masterDetail;
        if (!masterDetail?.renderer) {
            return options as Partial<GridOptions>;
        }

        return {
            ...options,
            masterDetail: {
                ...masterDetail,
                renderer: this.adaptDetailRenderer(masterDetail.renderer),
            },
        } as Partial<GridOptions>;
    }

    /**
     * Destroys every currently-mounted component/embedded view and stops
     * observing. Call exactly once, when the owning grid is torn down.
     * Deliberately unconditional (does not wait on the MutationObserver):
     * `disconnect()` drops any in-flight mutation records, so relying on it
     * for final teardown would risk leaking whatever hadn't been flushed yet.
     */
    dispose(): void {
        this.observer?.disconnect();
        this.observer = undefined;

        for (const [element, mount] of this.mounts) {
            this.destroyMount(mount);
            this.mounts.delete(element);
        }
    }

    private adaptColumn(column: GridColumnDef): ColumnDef {
        const { renderer, children, ...rest } = column;
        const adapted = { ...rest } as ColumnDef;

        // A built-in renderer selected by name (`renderer: 'country'`), a
        // configured one (`{ name, options }`), or a bare display function all
        // pass through untouched — there is nothing Angular-flavoured to adapt.
        // Only the slot map needs converting.
        //
        // The order matters. A string is truthy and `'country'.display` is
        // `undefined`, so running the per-slot rebuild over one would produce an
        // object of eight undefined slots, which the core reads as "slot map
        // with no display" and silently falls back to the column's inferred
        // renderer. The named renderer would vanish with no error anywhere.
        if (isRendererSlotMap(renderer)) {
            // Adapted per-slot (rather than via a generic loop over the
            // slot names) so each call keeps its own TParams/TOutput pair —
            // looping over a union of keys would force `adaptRenderer` to
            // accept the union of every slot's renderer type at once, which
            // doesn't type-check (an EditorRendererParams renderer isn't
            // assignable where a TooltipRendererParams renderer is expected).
            const adaptedRenderer: Partial<ColumnRendererMap> = {
                display: this.adaptRenderer(renderer.display),
                editor: this.adaptRenderer(renderer.editor),
                option: this.adaptRenderer(renderer.option),
                filter: this.adaptRenderer(renderer.filter),
                tooltip: this.adaptRenderer(renderer.tooltip),
                group: this.adaptRenderer(renderer.group),
                header: this.adaptRenderer(renderer.header),
                summary: this.adaptRenderer(renderer.summary),
            };
            adapted.renderer = adaptedRenderer as any;
        } else if (renderer) {
            adapted.renderer = renderer as ColumnDef['renderer'];
        }

        if (children) {
            adapted.children = children.map((child) => this.adaptColumn(child));
        }

        return adapted;
    }

    private adaptRenderer<TParams, TOutput extends RendererOutput | HTMLElement>(
        renderer: CellRenderer<TParams, TOutput> | undefined,
    ): ((params: TParams) => TOutput) | undefined {
        if (!renderer) {
            return undefined;
        }

        if (isComponentRendererSpec(renderer)) {
            return (params: TParams) => this.mountComponent(renderer, params) as unknown as TOutput;
        }

        if (isTemplateRendererSpec(renderer)) {
            return (params: TParams) => this.mountTemplate(renderer, params) as unknown as TOutput;
        }

        if (renderer instanceof TemplateRef) {
            return (params: TParams) => this.mountTemplate({ template: renderer }, params) as unknown as TOutput;
        }

        if (this.isComponentType(renderer)) {
            return (params: TParams) => this.mountComponent({ component: renderer }, params) as unknown as TOutput;
        }

        if (typeof renderer === 'function') {
            return renderer;
        }

        return undefined;
    }

    private isComponentType(value: unknown): value is import('@angular/core').Type<unknown> {
        return typeof value === 'function' && !!(value as { readonly ɵcmp?: unknown }).ɵcmp;
    }

    private mountComponent<TParams>(
        spec: { component: import('@angular/core').Type<unknown>; inputs?: (params: TParams) => Record<string, unknown> },
        params: TParams,
    ): HTMLElement {
        const componentRef = createComponent(spec.component, {
            environmentInjector: this.environmentInjector,
            elementInjector: this.elementInjector,
        });

        const normalizedParams = this.normalizeRendererParams(params);
        const inputs = spec.inputs ? spec.inputs(normalizedParams) : this.inferInputs(componentRef, normalizedParams);
        for (const [key, value] of Object.entries(inputs)) {
            this.setComponentInput(componentRef, key, value);
        }

        this.setComponentInput(componentRef, 'params', normalizedParams);

        // Attaching to ApplicationRef is what makes this component
        // participate in normal change detection (zone triggers, async
        // pipe, etc.) for as long as it stays mounted — required for any
        // interactivity inside the component itself (clicks, forms, ...).
        this.appRef.attachView(componentRef.hostView);
        componentRef.changeDetectorRef.detectChanges();

        this.invokeLifecycle(componentRef.instance, 'pgGridInit', normalizedParams);
        this.invokeLifecycle(componentRef.instance, 'pgGridRefresh', normalizedParams);

        const element = componentRef.location.nativeElement as HTMLElement;
        this.mounts.set(element, { kind: 'component', ref: componentRef });
        return element;
    }

    private setComponentInput<TComponent>(
        componentRef: ComponentRef<TComponent>,
        key: string,
        value: unknown,
    ): void {
        try {
            componentRef.setInput(key, value);
            return;
        } catch {
            const instance = componentRef.instance as Record<string, unknown>;
            instance[key] = value;
        }
    }

    private normalizeRendererParams<TParams>(params: TParams): TParams & { value?: unknown; rawValue?: unknown } {
        const normalized = { ...(params as Record<string, unknown>) };
        const option = normalized['option'];

        if (normalized['value'] === undefined && option && typeof option === 'object') {
            const optionValue = (option as { value?: unknown }).value;
            normalized['value'] = optionValue;
            normalized['rawValue'] = optionValue;
        }

        return normalized as TParams & { value?: unknown; rawValue?: unknown };
    }

    private inferInputs<TComponent, TParams>(
        componentRef: ComponentRef<TComponent>,
        params: TParams,
    ): Record<string, unknown> {
        const instance = componentRef.instance as Record<string, unknown>;
        const inputs: Record<string, unknown> = {};
        const paramBag = params as Record<string, unknown>;
        const row = paramBag['row'] && typeof paramBag['row'] === 'object'
            ? paramBag['row'] as Record<string, unknown>
            : undefined;

        for (const key of Object.keys(instance)) {
            if (key === '__ngContext__' || key === 'constructor') {
                continue;
            }

            if (paramBag[key] !== undefined) {
                inputs[key] = paramBag[key];
                continue;
            }

            if (row && row[key] !== undefined) {
                inputs[key] = row[key];
                continue;
            }

            if (key === 'seed' && row && row['id'] !== undefined) {
                inputs[key] = row['id'];
                continue;
            }

            if (key === 'value' && paramBag['value'] !== undefined) {
                inputs[key] = paramBag['value'];
            }
        }

        return inputs;
    }

    private invokeLifecycle<TParams>(
        instance: unknown,
        lifecycle: GridLifecycleMethod,
        params: TParams,
    ): void {
        const candidate = (instance as Record<string, unknown> | null)?.[lifecycle];
        if (typeof candidate === 'function') {
            (candidate as (params: TParams) => void).call(instance, params);
        }
    }

    private mountTemplate<TParams>(
        spec: {
            template: import('@angular/core').TemplateRef<RendererContext<TParams>>;
            context?: (params: TParams) => Record<string, unknown>;
        },
        params: TParams,
    ): HTMLElement {
        const normalizedParams = this.normalizeRendererParams(params);
        const context = {
            $implicit: normalizedParams,
            params: normalizedParams,
            ...(spec.context ? spec.context(normalizedParams) : {}),
        };

        const viewRef = spec.template.createEmbeddedView(context);
        this.appRef.attachView(viewRef);
        viewRef.detectChanges();

        const host = this.resolveTemplateHost(viewRef);
        this.mounts.set(host, { kind: 'template', ref: viewRef });
        return host;
    }

    /**
     * Uses the template's single root element directly when possible (so
     * `editor`/`filter` slots that expect the returned element to *be* the
     * control keep working); falls back to a wrapper `<div>` for templates
     * with multiple root nodes or text-only content.
     */
    private resolveTemplateHost(viewRef: EmbeddedViewRef<unknown>): HTMLElement {
        const [singleRoot] = viewRef.rootNodes;
        if (viewRef.rootNodes.length === 1 && singleRoot instanceof HTMLElement) {
            return singleRoot;
        }

        const host = document.createElement('div');
        host.classList.add('photon-grid__template-host');
        host.append(...viewRef.rootNodes);
        return host;
    }

    // ── Master/Detail ────────────────────────────────────────────────────────

    /**
     * Resolves any of the accepted {@link AngularDetailRenderer} forms to a
     * core `DetailRenderer`. Core forms (a `DetailComponent` class, a function,
     * an HTML string) are passed straight through — the wrapper only adds
     * Angular forms, it never intercepts what the core already understands.
     */
    private adaptDetailRenderer(renderer: AngularDetailRenderer): DetailRenderer {
        if (renderer instanceof TemplateRef) {
            return this.createTemplateDetailRenderer(renderer);
        }

        if (this.isComponentType(renderer)) {
            return this.createComponentDetailRenderer(renderer);
        }

        return renderer as DetailRenderer;
    }

    /**
     * Wraps an `<ng-template>` in a core `DetailComponent` class.
     *
     * A class (rather than a `(ctx) => HTMLElement` function) because only the
     * class form gets `destroy()` — an embedded view that is merely detached
     * from the DOM is still attached to `ApplicationRef` and would keep being
     * change-detected forever.
     *
     * `refresh` returns `true`: the template context reads `data`/`props`
     * through live accessors, so a change-detection pass *is* the whole update.
     * Re-creating the view would throw away scroll position, focus and any
     * component state inside the template for no benefit.
     */
    private createTemplateDetailRenderer(
        template: TemplateRef<DetailTemplateContext>,
    ): DetailComponentConstructor {
        // Captured so the returned class — which the core constructs with no
        // arguments — can still reach this adapter's ApplicationRef.
        const adapter = this;

        return class TemplateDetailRenderer implements DetailComponent {
            private viewRef?: EmbeddedViewRef<DetailTemplateContext>;

            init(ctx: DetailContext): HTMLElement {
                const viewRef = template.createEmbeddedView(adapter.buildDetailTemplateContext(ctx));

                // Attaching to ApplicationRef is what makes the template
                // participate in normal change detection (zone triggers, async
                // pipe, event bindings) for as long as the row stays expanded.
                adapter.appRef.attachView(viewRef);
                viewRef.detectChanges();

                this.viewRef = viewRef;

                const host = document.createElement('div');
                host.className = 'photon-grid__detail-host';
                host.append(...viewRef.rootNodes);
                return host;
            }

            refresh(): boolean {
                if (!this.viewRef) {
                    return false;
                }
                this.viewRef.detectChanges();
                return true;
            }

            destroy(): void {
                if (!this.viewRef) {
                    return;
                }
                adapter.appRef.detachView(this.viewRef);
                this.viewRef.destroy();
                this.viewRef = undefined;
            }
        };
    }

    /**
     * Wraps an Angular `@Component` in a core `DetailComponent` class. The
     * instance is created once per expanded row and updated in place on
     * refresh — the core's detail lifecycle has real update/teardown hooks, so
     * none of the mount-per-invocation machinery cell renderers need applies here.
     */
    private createComponentDetailRenderer(component: Type<unknown>): DetailComponentConstructor {
        const adapter = this;

        return class ComponentDetailRenderer implements DetailComponent {
            private ref?: ComponentRef<unknown>;

            init(ctx: DetailContext): HTMLElement {
                const ref = createComponent(component, {
                    environmentInjector: adapter.environmentInjector,
                    elementInjector: adapter.elementInjector,
                });

                adapter.applyDetailInputs(ref, ctx);
                adapter.appRef.attachView(ref.hostView);
                ref.changeDetectorRef.detectChanges();

                this.ref = ref;
                return ref.location.nativeElement as HTMLElement;
            }

            refresh(ctx: DetailContext): boolean {
                if (!this.ref) {
                    return false;
                }
                adapter.applyDetailInputs(this.ref, ctx);
                this.ref.changeDetectorRef.detectChanges();
                return true;
            }

            destroy(): void {
                if (!this.ref) {
                    return;
                }
                adapter.appRef.detachView(this.ref.hostView);
                this.ref.destroy();
                this.ref = undefined;
            }
        };
    }

    /**
     * Builds the template locals, with `data` and `props` as accessors onto the
     * core context rather than snapshots — that is what keeps a `let-data`
     * binding current across row transactions without rebuilding the view.
     *
     * There is no per-renderer context mapper: extra locals belong in
     * `masterDetail.props`, which reaches the template as `let-props`.
     */
    private buildDetailTemplateContext(ctx: DetailContext): DetailTemplateContext {
        const context = { $implicit: ctx, ctx } as DetailTemplateContext;

        Object.defineProperties(context, {
            data: { get: () => ctx.data, enumerable: true },
            props: { get: () => ctx.props, enumerable: true },
        });

        return context;
    }

    /**
     * Feeds `ctx`/`data`/`props` into a detail component. Anything else the
     * component needs comes from `masterDetail.props`, which arrives as the
     * `props` input.
     */
    private applyDetailInputs(ref: ComponentRef<unknown>, ctx: DetailContext): void {
        this.setComponentInput(ref, 'ctx', ctx);
        this.setComponentInput(ref, 'data', ctx.data);
        this.setComponentInput(ref, 'props', ctx.props);
    }

    private cleanupRemovedNode(node: Node): void {
        if (!(node instanceof HTMLElement)) {
            return;
        }

        const directMount = this.mounts.get(node);
        if (directMount) {
            this.mounts.delete(node);
            this.destroyMount(directMount);
        }

        // The core may remove an ancestor (e.g. an entire recycled row)
        // rather than the mounted element itself; sweep for any tracked
        // host contained in the removed subtree.
        if (node.childElementCount === 0) {
            return;
        }
        for (const [element, mount] of this.mounts) {
            if (node.contains(element)) {
                this.mounts.delete(element);
                this.destroyMount(mount);
            }
        }
    }

    private destroyMount(mount: RendererMount): void {
        if (mount.kind === 'component') {
            this.invokeLifecycle(mount.ref.instance, 'pgGridDestroy', undefined);
            const viewRef = mount.ref.hostView;
            this.appRef.detachView(viewRef);
            mount.ref.destroy();
            return;
        }

        const viewRef = mount.ref;
        this.appRef.detachView(viewRef);
        mount.ref.destroy();
    }
}

// packages/photon-grid-react/src/react-renderer-adapter.tsx
import { createElement, type ComponentType, type JSX } from 'react';
import { createPortal } from 'react-dom';
import { createRoot, type Root } from 'react-dom/client';

import type {
  ColumnDef,
  ColumnDefInput,
  ColumnRenderer,
  DetailComponent,
  DetailComponentConstructor,
  DetailContext,
  DetailRenderer,
  GridOptions,
  MasterDetailConfig,
  RendererOutput,
} from 'photon-grid-core';

export interface ReactRendererSpec {
  kind: 'component';
  component: ComponentType<Record<string, unknown>>;
  props?: (params: unknown) => Record<string, unknown>;
}

/**
 * `masterDetail.renderer` as accepted by the React wrapper: a React component
 * passed directly, or anything the core already accepts (a `DetailComponent`
 * class, a `(ctx) => HTMLElement | string` function, a static HTML string).
 *
 * ```tsx
 * renderer: OrderDetail                                  // a React component
 * renderer: (ctx) => `<h2>${ctx.data.account}</h2>`      // core: HTML from a function
 * renderer: '<h2>Details</h2>'                           // core: a static HTML string
 * ```
 *
 * A bare function is treated as a React component only when its name is
 * capitalised — the same convention {@link isComponentRenderer} uses for
 * cells, since a lowercase React component is indistinguishable from a core
 * function renderer. For that case, wrap it explicitly with
 * {@link createReactDetailRenderer}.
 */
export type ReactDetailRenderer = ComponentType<Record<string, unknown>> | DetailRenderer;

/** Core `MasterDetailConfig` with `renderer` widened to the React forms above. */
export type ReactMasterDetailConfig = Omit<MasterDetailConfig, 'renderer'> & {
  renderer?: ReactDetailRenderer;
};

/**
 * Core `GridOptions` with `masterDetail.renderer` widened to accept React
 * components. Assignment-compatible with the core type, so an existing
 * `GridOptions` object passes through unchanged.
 */
export type PhotonGridOptions = Omit<GridOptions, 'masterDetail'> & {
  masterDetail?: ReactMasterDetailConfig;
};

type RendererSlotValue = ((params: unknown) => RendererOutput) | ReactRendererSpec | ComponentType<Record<string, unknown>> | undefined;

/**
 * React column definition. Built on the core's {@link ColumnDefInput}, so it
 * inherits the same relaxed contract: **only `field` is required**; `colId`,
 * `header` and `type` are optional and defaulted by the core (auto `colId`,
 * header from the field in Title Case, `type` defaulting to `'string'`). The
 * `renderer` slots additionally accept React components/specs.
 */
type PhotonGridColumnDef = Omit<ColumnDefInput, 'renderer'> & {
  /**
   * Accepts everything the core does — a built-in renderer by name
   * (`'country'`), a configured one (`{ name, options }`), a bare display
   * function — plus the React component/spec forms in the slot map, which the
   * adapter converts to plain functions.
   */
  renderer?: ColumnRenderer | {
    display?: RendererSlotValue;
    editor?: RendererSlotValue;
    option?: RendererSlotValue;
    filter?: RendererSlotValue;
    tooltip?: RendererSlotValue;
    group?: RendererSlotValue;
    header?: RendererSlotValue;
    summary?: RendererSlotValue;
  };
};

function isComponentRenderer(value: RendererSlotValue): value is ReactRendererSpec | ComponentType<Record<string, unknown>> {
  if (!value) {
    return false;
  }

  if (typeof value === 'object' && 'kind' in value && value.kind === 'component') {
    return true;
  }

  if (typeof value === 'object' && value !== null && '$$typeof' in value) {
    return true;
  }

  if (typeof value === 'function') {
    return /^[A-Z]/.test(value.name ?? '');
  }

  return false;
}

type RendererEntry = {
  key: string;
  host: HTMLElement;
  component: ComponentType<Record<string, unknown>>;
  props?: Record<string, unknown>;
};

export class ReactRendererAdapter {
  private root?: Root;
  private container?: HTMLElement;
  private readonly entries = new Map<string, RendererEntry>();
  private observer?: MutationObserver;
  private pendingFlush = false;

  observe(host: HTMLElement): void {
    if (this.observer) {
      return;
    }

    this.container = document.createElement('div');
    this.container.className = 'photon-grid-react__portal';
    this.container.style.position = 'absolute';
    this.container.style.inset = '0';
    this.container.style.pointerEvents = 'none';
    this.container.style.overflow = 'hidden';
    host.appendChild(this.container);

    this.root = createRoot(this.container);
    this.flush();

    this.observer = new MutationObserver((mutations) => {
      for (const mutation of mutations) {
        for (const removedNode of Array.from(mutation.removedNodes)) {
          this.unmountNode(removedNode);
        }
      }
    });

    this.observer.observe(host, { childList: true, subtree: true });
  }

  adaptColumns(columns: PhotonGridColumnDef[]): ColumnDef[] {
    return columns.map((column) => {
      const { renderer } = column;
      if (!renderer) {
        return column as ColumnDef;
      }

      // A built-in renderer selected by name (`renderer: 'country'`), a
      // configured one (`{ name, options }`), or a bare display function passes
      // straight through — there is nothing React-flavoured to adapt.
      //
      // This must precede the slot loop: a string is truthy but has no slots,
      // so the loop below would replace it with an empty object, which the core
      // reads as "slot map with no display" and silently falls back to the
      // column's inferred renderer. The named renderer would vanish with no
      // error anywhere.
      if (typeof renderer === 'string' || typeof renderer === 'function' || 'name' in renderer) {
        return column as ColumnDef;
      }

      const adaptedRenderer: Record<string, unknown> = {};
      const slots = ['display', 'editor', 'option', 'filter', 'tooltip', 'group', 'header', 'summary'] as const;

      for (const slot of slots) {
        const value = renderer[slot];
        if (isComponentRenderer(value)) {
          adaptedRenderer[slot] = (params: unknown) => this.mountComponent(value, params);
        } else if (typeof value === 'function') {
          adaptedRenderer[slot] = value;
        }
      }

      return {
        ...column,
        renderer: adaptedRenderer,
      } as ColumnDef;
    });
  }

  /**
   * Converts React-flavoured grid options into what the core accepts.
   *
   * Currently that is `masterDetail.renderer`: a React component is wrapped in
   * a core `DetailComponent` class that owns its own React root and unmounts
   * it in `destroy()`.
   *
   * Unlike cell renderers, detail rows need no portal bookkeeping and no
   * `MutationObserver`: the core's detail lifecycle hands us explicit
   * `init`/`refresh`/`destroy` hooks, and there is at most one mounted detail
   * per expanded row.
   *
   * Returns the original object untouched when there is nothing React to
   * adapt, so the common case allocates nothing.
   */
  adaptOptions(options: Partial<PhotonGridOptions>): Partial<GridOptions> {
    const masterDetail = options.masterDetail;
    if (!masterDetail?.renderer) {
      return options as Partial<GridOptions>;
    }

    return {
      ...options,
      masterDetail: {
        ...masterDetail,
        renderer: adaptDetailRenderer(masterDetail.renderer),
      },
    } as Partial<GridOptions>;
  }

  dispose(): void {
    this.observer?.disconnect();
    this.observer = undefined;

    const root = this.root;

    this.root = undefined;

    queueMicrotask(() => {
        root?.unmount();
    });
    this.root = undefined;

    this.entries.clear();
    this.container?.remove();
    this.container = undefined;
    this.pendingFlush = false;
  }

  private mountComponent(spec: ReactRendererSpec | ComponentType<Record<string, unknown>>, params: unknown): HTMLElement {
    const key = this.getRendererKey(params);

    if (key) {
      const existing = this.entries.get(key);
      if (existing) {
        const props = this.getRendererProps(spec, params);
        if (existing.component === this.getComponent(spec) && this.propsMatch(existing.props, props)) {
          return existing.host;
        }

        existing.component = this.getComponent(spec);
        existing.props = props;
        this.flush();
        return existing.host;
      }
    }

    const host = document.createElement('div');
    host.className = 'photon-grid-react__renderer-host';
    host.style.width = '100%';
    host.style.height = '100%';
    host.style.pointerEvents = 'auto';
    host.style.display = 'block';

    if (key) {
      this.entries.set(key, {
        key,
        host,
        component: this.getComponent(spec),
        props: this.getRendererProps(spec, params),
      });
      this.flush();
    }

    return host;
  }

  private flush(): void {
    if (!this.root || !this.container || this.pendingFlush) {
      return;
    }

    this.pendingFlush = true;

    requestAnimationFrame(() => {
      this.pendingFlush = false;
      if (!this.root) {
        return;
      }

      this.root.render(createElement(this.renderFrame, { entries: Array.from(this.entries.values()) }));
    });
  }

  private renderFrame(props: { entries: RendererEntry[] }): JSX.Element {
    return createElement(
      'div',
      { className: 'photon-grid-react__frame', style: { display: 'contents' } },
      props.entries.map((entry) => createElement(
        'div',
        { key: entry.key, style: { display: 'contents' } },
        createPortal(createElement(entry.component, entry.props ?? {}), entry.host),
      )),
    );
  }

  private getComponent(spec: ReactRendererSpec | ComponentType<Record<string, unknown>>): ComponentType<Record<string, unknown>> {
    if (typeof spec === 'object' && spec !== null && 'kind' in spec) {
      return spec.component;
    }

    return spec as ComponentType<Record<string, unknown>>;
  }

  private getRendererProps(spec: ReactRendererSpec | ComponentType<Record<string, unknown>>, params: unknown): Record<string, unknown> {
    if (typeof spec === 'object' && spec !== null && 'kind' in spec && typeof spec.props === 'function') {
      return {
        ...this.getBaseProps(params),
        ...spec.props(params),
      };
    }

    return this.getBaseProps(params);
  }

  private getBaseProps(params: unknown): Record<string, unknown> {
    if (!params || typeof params !== 'object') {
      return {};
    }

    const candidate = params as Record<string, unknown>;

    return {
      ...candidate,
      row: candidate.row ?? candidate.data,
      rowIndex: candidate.rowIndex,
      value: candidate.value,
      colDef: candidate.colDef,
      api: candidate.api,
      colIndex: candidate.colIndex,
    };
  }

  private propsMatch(previousProps: Record<string, unknown> | undefined, nextProps: Record<string, unknown>): boolean {
    if (!previousProps) {
      return false;
    }

    const previousKeys = Object.keys(previousProps);
    const nextKeys = Object.keys(nextProps);

    if (previousKeys.length !== nextKeys.length) {
      return false;
    }

    for (const key of previousKeys) {
      if (!Object.prototype.hasOwnProperty.call(nextProps, key)) {
        return false;
      }

      if (previousProps[key] !== nextProps[key]) {
        return false;
      }
    }

    return true;
  }

  private getRendererKey(params: unknown): string | null {
    if (!params || typeof params !== 'object') {
      return null;
    }

    const candidate = params as {
      rowIndex?: number;
      colIndex?: number;
      colDef?: { colId?: string; field?: string };
    };

    const colId = candidate.colDef?.colId ?? candidate.colDef?.field ?? 'cell';
    const rowIndex = typeof candidate.rowIndex === 'number' ? candidate.rowIndex : 'unknown';
    const colIndex = typeof candidate.colIndex === 'number' ? candidate.colIndex : 'unknown';

    return `${colId}:${rowIndex}:${colIndex}`;
  }

  private unmountNode(node: Node): void {
    if (node instanceof HTMLElement) {
      this.unmountHost(node);
      node.querySelectorAll<HTMLElement>('*').forEach((child) => {
        this.unmountHost(child);
      });
    }
  }

  private unmountHost(host: HTMLElement): void {
    for (const [key, entry] of this.entries.entries()) {
      key
      if (entry.host === host) {
        requestAnimationFrame(() => {
            this.flush();
        });
        break;
      }
    }
  }
}

export type { PhotonGridColumnDef };

// ── Master/Detail ────────────────────────────────────────────────────────────

/**
 * Resolves a {@link ReactDetailRenderer} to a core `DetailRenderer`. Core
 * forms — a `DetailComponent` class, a function, an HTML string — pass
 * straight through; the wrapper only adds the React form.
 */
function adaptDetailRenderer(renderer: ReactDetailRenderer): DetailRenderer {
  // Probed as `unknown` rather than through the union: each check below
  // narrows by exclusion, and by the last one TypeScript has reduced the union
  // to a shape that no longer admits the structural test being made.
  const candidate: unknown = renderer;

  // A memo/forwardRef component is an object carrying React's brand symbol.
  if (typeof candidate === 'object' && candidate !== null && '$$typeof' in candidate) {
    return createReactDetailRenderer(candidate as ComponentType<Record<string, unknown>>);
  }

  if (typeof candidate === 'function' && /^[A-Z]/.test(candidate.name)) {
    return createReactDetailRenderer(candidate as ComponentType<Record<string, unknown>>);
  }

  return renderer as DetailRenderer;
}

/** Props every detail component receives. Anything else comes from `masterDetail.props`, delivered as the `props` prop. */
function detailProps(ctx: DetailContext): Record<string, unknown> {
  return { ctx, data: ctx.data, props: ctx.props, api: ctx.api, rowNode: ctx.rowNode };
}

/**
 * Wraps a React component in a core `DetailComponent` class.
 *
 * A class (rather than a `(ctx) => HTMLElement` function) because only the
 * class form gets `destroy()` — a React root that is merely detached from the
 * DOM is never unmounted, so its effects and subscriptions would outlive the
 * collapsed row.
 *
 * Each expanded row gets its own root mounted into `ctx.containerEl`. `refresh`
 * re-renders that root in place and returns `true`, so React reconciles rather
 * than the core tearing the component down and rebuilding it.
 *
 * Exported for the one case the bare form cannot express: a lowercase-named
 * function component, which is indistinguishable from a core function
 * renderer. `renderer: createReactDetailRenderer(myDetail)` settles it.
 */
export function createReactDetailRenderer(
  component: ComponentType<Record<string, unknown>>,
): DetailComponentConstructor {
  return class ReactDetailRenderer implements DetailComponent {
    private root?: Root;

    init(ctx: DetailContext): void {
      this.root = createRoot(ctx.containerEl);
      this.root.render(createElement(component, detailProps(ctx)));
    }

    refresh(ctx: DetailContext): boolean {
      if (!this.root) {
        return false;
      }
      this.root.render(createElement(component, detailProps(ctx)));
      return true;
    }

    destroy(): void {
      const root = this.root;
      this.root = undefined;
      // Deferred: the core may call this from inside a React commit (an event
      // handler that collapsed the row), and unmounting a root synchronously
      // during render is a React error.
      queueMicrotask(() => root?.unmount());
    }
  };
}
